config/routes.rb
Rails.application.routes.draw do
  # root to: 'blockchains#index'
  root to: 'blocks#index'

  resources :blocks,       only: [:index] do
    collection do
      get 'confirmation'
      get 'list_api'
      get 'list_sync'
    end
  end

  resources :transactions, only: [:create]

  resources :nodes, only: [:index, :create, :destroy] do
    collection do
      get 'list_api'
      get 'list_sync'
    end
  end

  # resources :blockchains, only: [:index, :new, :create, :show] do
  #   post 'transactions/generate', to: 'transactions#generate'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/node.rb
class Node < ApplicationRecord

  class << self
    # bundle exec rails runner "Node.list_sync"
    def list_sync
      nodes = Node.all

      nodes.each do |node|
        begin
          response = RestClient.get("#{node.end_point}#{node.list_path}")
          response_body = JSON.parse(response.body).deep_symbolize_keys

          response_body[:nodes].each do |node|
            Node.create_with(
              name:      node[:name],
              list_path: node[:list_path]
            ).find_or_create_by!(
              end_point: node[:end_point],
            )
          end
        rescue => exception
          puts "[ ---------- exception ---------- ]"; exception.message.tapp;
        end
      end
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  permits :name, :end_point, :list_path

  def index
    @nodes = Node.order(created_at: :desc)
    @node  = Node.new
  end

  def create(node)
    @node = Node.new(node)
    @node.save!

    redirect_to nodes_path, notice: 'ノードを登録しました。'
  end

  def list_sync
    Node.list_sync

    redirect_to nodes_path and return
  end

  def list_api
    nodes = Node.all

    render json: { nodes: nodes } and return
  end

  def destroy(id)
    node = Node.find_by(id: id)
    node.destroy

    redirect_to nodes_path, notice: 'ノードを削除しました。'
  end
end

app/views/nodes/index.html.haml
%h2= link_to 'Listing Nodes', nodes_path

%p= link_to 'ノード同期', list_sync_nodes_path

= form_for @node, url: nodes_path do |f|
  .field
    = f.label :name
    = f.text_field :name, size: 30
  .field
    = f.label :end_point
    = f.text_field :end_point, size: 30
  .field
    = f.label :list_path
    = f.text_field :list_path, size: 30
  .actions
    = f.submit 'Save'

%table
  %thead
    %tr
      %th name
      %th end_point
      %th list_path
      %th
  %tbody
    - @nodes.each do |node|
      %tr
        %td= node.name
        %td= node.end_point
        %td= node.list_path
        %td= link_to 'Delete', node_path(node), method: :delete, data: { confirm: "「#{node.name}」を削除します。よろしいですか？" }