config/routes.rb
Rails.application.routes.draw do
  # root to: 'blockchains#index'
  root to: 'blocks#index'

  resources :blocks,       only: [:index] do
    collection do
      get 'confirmation'
      get 'list_api'
      get 'list_sync'
    end
  end

  resources :transactions, only: [:create]

  resources :nodes, only: [:index, :create, :destroy] do
    collection do
      get 'list_api'
      get 'list_sync'
    end
  end

  # resources :blockchains, only: [:index, :new, :create, :show] do
  #   post 'transactions/generate', to: 'transactions#generate'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :blockchain, optional: true
  has_many   :trade_transactions
  has_many   :transaction_outputs

  DIFFICULTY = '0'

  class << self
    def proof_of_work(block: nil)
      nonce                 = 0
      proof_of_work_history = []

      loop do
        sha256_hash = Block.calc_hash_with_nonce(block: block, nonce: nonce)

        proof_of_work_history << sha256_hash

        if sha256_hash.start_with?(Block::DIFFICULTY)
          return sha256_hash, nonce, proof_of_work_history
        else
          nonce += 1
        end
      end
    end

    def calc_hash_with_nonce(block: nil, nonce: 0)
      Digest::SHA256.hexdigest({
        timestamp:     block.generate_at.to_i,
        transactions:  block.trade_transactions.pluck(:hash_key).to_json,
        previous_hash: block.previous_hash,
        nonce:         nonce
      }.to_json)
    end

    # bundle exec rails runner "Block.list_sync"
    def list_sync
      nodes = Node.all

      nodes.each do |node|
        begin
          response = RestClient.get("#{node.end_point}/blocks/list_api")
          response_body = JSON.parse(response.body).deep_symbolize_keys

          response_body[:blocks].each do |block|
            mine_block = Block.create_with(
              blockchain_id:         block[:blockchain_id],
              index:                 block[:index],
              generate_at:           block[:generate_at],
              nonce:                 block[:nonce],
              previous_hash:         block[:previous_hash],
              proof_of_work_history: block[:proof_of_work_history],
              confirmation_count:    block[:confirmation_count],
            ).find_or_create_by!(
              hash_key: block[:hash_key],
            )

            if block[:transactions].present?
              block[:transactions].each do |transaction|
                trade_transaction = TradeTransaction.create_with(
                  blockchain_id:  transaction[:blockchain_id],
                  block_id:       mine_block.id,
                  sender_address: transaction[:sender_address],
                  input_amount:   transaction[:input_amount],
                  generate_at:    transaction[:generate_at],
                ).find_or_create_by!(
                  hash_key: transaction[:hash_key],
                )

                if block[:transaction_outputs].present?
                  block[:transaction_outputs].each do |transaction|
                    TransactionOutput.create_with(
                      blockchain_id:        transaction[:blockchain_id],
                      block_id:             mine_block.id,
                      receiver_address:     transaction[:receiver_address],
                      output_amount:        transaction[:output_amount],
                      generate_at:          transaction[:generate_at],
                      trade_transaction_id: trade_transaction.id,
                    ).find_or_create_by!(
                      hash_key: transaction[:hash_key],
                    )
                  end
                end
              end
            end
          end

          if response_body[:confirmations].present?
            response_body[:confirmations].each do |confirmation|
              Confirmation.create_with(
                host:   confirmation[:host],
                status: confirmation[:status],
              ).find_or_create_by!(
                block_hash_key: confirmation[:block_hash_key],
              )
            end
          end
        rescue => exception
          puts "[ ---------- exception ---------- ]"; exception.message.tapp;
        end
      end
    end

    # bundle exec rails runner "Block.confirmation_block"
    def confirmation_block
      blocks = Block.all

      blocks.each do |block|
        if Block.calc_hash_with_nonce(block: block, nonce: block.nonce.to_i).start_with?(Block::DIFFICULTY)
          Confirmation.find_or_create_by!(
            block_hash_key: block.hash_key,
            host:           Settings.http_host,
            status:         true,
          )

          block.update!(confirmation_count: Confirmation.where(block_hash_key: block.hash_key).count)
        end
      end
    end
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @blockchain = Blockchain.find_by(unique_key: Blockchain::UNIQUE_KEY)
    # @blocks     = Block.where(blockchain_id: @blockchain.id).order(generate_at: :desc).includes(trade_transactions: :transaction_outputs).all
    @blocks     = Block.order(id: :desc).includes(trade_transactions: :transaction_outputs).all
  end

  def confirmation
    Block.confirmation_block

    redirect_to blocks_path and return
  end

  def list_sync
    Block.list_sync

    redirect_to blocks_path and return
  end

  def list_api
    block_array = []
    blocks = Block.includes(:trade_transactions).all

    blocks.each do |block|
      block_array << block.attributes.merge(transactions: block.trade_transactions, transaction_outputs: block.transaction_outputs)
    end

    render json: { blocks: block_array, confirmations: Confirmation.all } and return
  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/index.html.haml
%h3= @blockchain.name

%p= link_to 'ノード一覧', nodes_path
%p= link_to '取引確認', confirmation_blocks_path
%p= link_to 'ブロック同期', list_sync_blocks_path

%hr

%h2 取引作成

= form_tag transactions_path do
  %p
    %b 残高:
    = number_with_delimiter(TradeTransaction::COMMON_BALANCE)
  %p
    .field
      %b 送信元アドレス:
      = text_field_tag :sender_address, '111'
  %p
    .field
      %b 送信先アドレス:
      = text_field_tag :receiver_address, '222'
  %p
    .field
      %b 送信額:
      = text_field_tag :output_amount, '100'

  .actions
    = submit_tag '送信', data: { confirm: '送金します。よろしいですか？' }

%hr

%h2 取引一覧

- @blocks.each do |block|
  %h3= "ブロック #{block.id}"

  %table
    %thead
      %tr
        %th id
        %td= block.id
      %tr
        %th blockchain_id
        %td= block.blockchain_id
      %tr
        %th hash_key
        %td= block.hash_key
      %tr
        %th index
        %td= block.index
      %tr
        %th nonce
        %td= block.nonce
      %tr
        %th previous_hash
        %td= block.previous_hash
      %tr
        %th generate_at
        %td= block.generate_at
      %tr
        %th confirmation_count
        %td= block.confirmation_count
      %tr
        %th proof_of_work_history
        %td= block.proof_of_work_history
      %tr
        %th transactions
        %td
          - block.trade_transactions.each do |trade|
            %b id:
            = trade.id
            %br
            %b blockchain_id:
            = trade.blockchain_id
            %br
            %b block_id:
            = trade.block_id
            %br
            %b hash_key:
            = trade.hash_key
            %br
            %b sender_address:
            = trade.sender_address
            %br
            %b input_amount:
            = trade.input_amount
            %br
            %b generate_at:
            = trade.generate_at
            %br
            [output]
            %br
            - trade.transaction_outputs.each do |output|
              %b hash_key:
              = output.hash_key
              %br
              %b receiver_address:
              = output.receiver_address
              %br
              %b output_amount:
              = output.output_amount
              %br